[package]
name = "core-error"
version = "0.1.0"
authors = ["roblabla <unfiltered@roblab.la>"]
build = "build.rs"

[build-dependencies]
version_check = "0.9"

[features]
default = ["std"]
alloc = []
std = []